project_name: "simple_project"
task_name: "initial_step"
tags: 
 - simple_tag
configuration_path: "configs/train_config.yml"
s3_data_path: "s3://gisp/rosatom/ml_example/data"
output_data_folder: "./"
input_data_path: "data/raw/heart.csv"
splitting_params:
  validate_size: 0.1
  random_state: 3
feature_params:
  categorical_columns:
    - "Sex" 
    - "ChestPainType"
    - "FastingBS"
    - "RestingECG"
    - "ExerciseAngina"
    - "ST_Slope"
  numerical_columns:
    - "Age"
    - "RestingBP"
    - "Cholesterol"
    - "MaxHR"
    - "Oldpeak"
  target_column: "HeartDisease"
training_params:
  model_type: "LogisticRegression"
  random_state: 42
metric_file_path: "models/metrics.json"
local_model_save_path: "models/baseline_logreg.pkl"
model_s3_path: "s3://gisp/rosatom/ml_example/model/baseline_logreg.pkl"